apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-starter
  labels:
    app: express-api-starter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-api-starter
  template:
    metadata:
      labels:
        app: express-api-starter
    spec:
      containers:
      - name: api
        image: express-api-starter:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: express-api-starter
spec:
  selector:
    app: express-api-starter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
